CREATE TABLE IF NOT EXISTS TB_M_ROLE (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    code TEXT NOT NULL UNIQUE,
    name TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE TB_M_USER ADD COLUMN IF NOT EXISTS role_id UUID;

INSERT INTO TB_M_ROLE (code, name)
SELECT 'admin','Administrator' WHERE NOT EXISTS (SELECT 1 FROM TB_M_ROLE WHERE code='admin');
INSERT INTO TB_M_ROLE (code, name)
SELECT 'user','Regular User' WHERE NOT EXISTS (SELECT 1 FROM TB_M_ROLE WHERE code='user');
INSERT INTO TB_M_ROLE (code, name)
SELECT 'staff','Staff' WHERE NOT EXISTS (SELECT 1 FROM TB_M_ROLE WHERE code='staff');
INSERT INTO TB_M_ROLE (code, name)
SELECT 'courier','Courier' WHERE NOT EXISTS (SELECT 1 FROM TB_M_ROLE WHERE code='courier');


ALTER TABLE TB_M_USER ALTER COLUMN role_id SET NOT NULL;
ALTER TABLE TB_M_USER
  ADD CONSTRAINT fk_users_role FOREIGN KEY (role_id) REFERENCES TB_M_ROLE(id);